### ISSUE TITLE
Unable to install this dependency using gradle

### ISSUE THREAD

**Issue by perwezalamnewscorp** [energizedwork/webdriver-binaries-gradle-plugin#1]
I have been trying to install the webdriver binaries using this plugin but, it gets failed. Throwing an error.

I am using the below Gradle code for this. But its not working. Please try in your system and fin an issue if exist or need i to change anything init. I have taken this from Geb code repo

plugins {
    id "idea"
    id "groovy"
    id "com.energizedwork.webdriver-binaries" version "1.0"
    id "com.energizedwork.idea-base" version "1.2"
}

ext {
    // The drivers we want to use
    drivers = ["firefox", "chrome", "chromeHeadless"]

    ext {
        groovyVersion = '2.4.12'
        gebVersion = '2.0'
        seleniumVersion = '3.5.3'
        chromeDriverVersion = '2.32'
        geckoDriverVersion = '0.18.0'
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // If using Spock, need to depend on geb-spock
    testCompile "org.gebish:geb-spock:$gebVersion"
    testCompile("org.spockframework:spock-core:1.1-groovy-2.4") {
        exclude group: "org.codehaus.groovy"
    }
    testCompile "org.codehaus.groovy:groovy-all:$groovyVersion"

    // If using JUnit, need to depend on geb-junit (3 or 4)
    testCompile "org.gebish:geb-junit4:$gebVersion"

    // Drivers
    testCompile "org.seleniumhq.selenium:selenium-chrome-driver:$seleniumVersion"
    testCompile "org.seleniumhq.selenium:selenium-firefox-driver:$seleniumVersion"
}

webdriverBinaries {
    chromedriver chromeDriverVersion
    geckodriver geckoDriverVersion
}

drivers.each { driver ->
    task "${driver}Test"(type: Test) {
        outputs.upToDateWhen { false }  // Always run tests

        systemProperty "geb.build.reportsDir", reporting.file("geb/$name")
        systemProperty "geb.env", driver
    }
}

test {
    dependsOn drivers.collect { tasks["${it}Test"] }
    enabled = false
}

tasks.withType(Test) {
    maxHeapSize = "1g"
    jvmArgs '-XX:MaxMetaspaceSize=128m'
    testLogging {
        exceptionFormat = 'full'
    }
}

tasks.withType(GroovyCompile) {
    groovyOptions.forkOptions.memoryMaximumSize = '256m'
}

**Comment by erdi** [comment]
What is the error you are getting?

**Comment by perwezalamnewscorp** [comment]
<img width="1140" alt="screen shot 2017-10-27 at 4 19 52 pm" src="https://user-images.githubusercontent.com/19994714/32100779-c0726a72-bb32-11e7-9741-30c3820d3f0d.png">


I am getting this error shown in the screen shot. When commented this plugin then it works fine

**Comment by erdi** [comment]
Which version of Gradle are you using? You need to use 4.0 or newer for this plugin to work.

**Comment by perwezalamnewscorp** [comment]
<img width="546" alt="screen shot 2017-10-27 at 5 09 09 pm" src="https://user-images.githubusercontent.com/19994714/32102370-9b6eacf2-bb39-11e7-87ad-02c0faf8b082.png">


I am using very latest version. Please see the screen shot above to see all version

**Comment by erdi** [comment]
What you pasted is the version of Gradle on the command line which is not necessarily the same version as the one used by Intellij. Can you please share your settings in `File | Settings | Build, Execution, Deployment | Build Tools | Gradle` of IntelliJ?

**Comment by perwezalamnewscorp** [comment]
You are right. I updated the Gradle version to 4.2.1 (distributionUrl=https\://services.gradle.org/distributions/gradle-4.2.1-all.zip). And its working as expected.

Thank you so much for your help
