### ISSUE TITLE
Ability to provide alternative download servers

### ISSUE THREAD

**Issue by irstevenson** [energizedwork/webdriver-binaries-gradle-plugin#10]
For our organisation's build server, we don't have external access, therefore we host our own maven repo/proxy and also a HTTP server where we can download other dependencies (such as gradle wrappers, etc.). Therefore, it'd be rather helpful if rather than hardcoding the download endpoint - such as below - that there was  a config option to specify a template for the URL, or at least to set the baseURL.

https://github.com/energizedwork/webdriver-binaries-gradle-plugin/blob/ef1030853ba5c70ee2735a72e21529909e629fc7/src/main/groovy/com/energizedwork/gradle/webdriver/gecko/GeckoDriverDistributionInstaller.groovy#L36

**Comment by erdi** [comment]
I'm going to close this issue as the functionality you request will be available when #9 is implemented.
