### ISSUE TITLE
Question about ChromeDriver

### ISSUE THREAD

**Issue by MiguelAngel82** [energizedwork/webdriver-binaries-gradle-plugin#11]
Hello all.

I have a question about how this plugin works in regarding to ChromeDriver. Is needed to have installed any compatible version with ChromeDriver to use it?

In other words, I have installed the plugin in a Grail 3 app (Gradle app based), and I'm using ChromeDriver profile to execute tests. If the machine where this app is executed has not installed Chrome it fails because it cannot find Chrome:

`org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary`

So this is my question, is needed to have installed Chrome in this machine? If not, how this plugin do that? And if yes, is there any possibility to install it automatically?

Thanks in advance.

Regards,
Miguel.

**Comment by erdi** [comment]
This plugin is for installing driver binaries, like for example [ChromeDriver](http://chromedriver.chromium.org/), and not browsers, like for example chrome. A version of chrome browser has to be installed on the machine on which you wish to use ChromeDriver to drive that browser.

**Comment by MiguelAngel82** [comment]
Thank you for your response @erdi. It clarifies myself ;)
