### ISSUE TITLE
Support for PhantomJs driver

### ISSUE THREAD

**Issue by sdelamo** [energizedwork/webdriver-binaries-gradle-plugin#3]
Hello, 

Would it be possible to support phantomJs driver with this Gradle plugin?

thanks

**Comment by erdi** [comment]
Given that [it looks like PhantomJs will not be developed anymore](https://www.infoq.com/news/2017/04/Phantomjs-future-uncertain) and what seems like a better alternative for headless browser automation in [Headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome#drivers) I'm rather sceptical about adding support for something that is essentially deprecated.

**Comment by sdelamo** [comment]
Just for reference the link to PhantomJS project maintainer stepping down. 

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
