### ISSUE TITLE
Internet Explorer support

### ISSUE THREAD

**Issue by hermitmaster** [energizedwork/webdriver-binaries-gradle-plugin#7]
Thanks for the plugin, it's a big help. Any chance of support for Internet Explorer in the future? I work on a lot of enterprise projects where IE support and testing is still required.

**Comment by erdi** [comment]
I thought about it a bit but given that I personally don’t do IE test
automation I wanted the plugin to gather some traction to justify the
effort. Now that you it has been requested by you it’s probably time to
look into providing support for IE. And end to end testing it at AppVeyor
will be an interesting challenge.

**Comment by masterautomator** [comment]
@erdi 

+1 for IE support :) We need it too.

To give some additional info : I have just now converted a Maven Geb project to use Gradle using the sample build.gradle you provided which uses this plugin. (Part of the reason for the migration is the Sauce labs and Browser stack gradle plugins for Geb!!)

We need support for IE and your help is appreciated.

**Comment by masterautomator** [comment]
Awesome dude! I am gonna check it out right away. Thanks again @erdi

**Comment by masterautomator** [comment]
@erdi  I tried 1.3 version just now. 
Good news: it opens the IE browser now when I run with: .\gradlew ieTest

BUT, it seems like it's only downloading the 64 bit version of the IE driver. And I know we have issues with the 64 bit version and use the 32 bit version.

I haven't looked at the source code you wrote, but quickly speaking, is there support to specify the 32 bit vs 64 bit version of IE driver?

Thanks man!
======
Some details on my setup/config:

- id "com.energizedwork.webdriver-binaries" version "1.3"
- ieDriverVersion = '3.8.0'
- drivers = ["firefox", "chrome", "chromeHeadless", "ie"]

webdriverBinaries {
    chromedriver chromeDriverVersion
    geckodriver geckoDriverVersion
    **iedriverserver  ieDriverVersion**
}

And running with:
**.\gradlew ieTest**

**Comment by erdi** [comment]
Thanks for testing it for me.

No it's not possible to specify the architecture as currently the plugin detects the architecture of the OS the build runs on and uses the version of IEDriverServer for that architecture. Can you please create a new issue to add support for specifying the architecture for IEDriverServer in plugin config?

**Comment by masterautomator** [comment]
@erdi  
Done. Thanks again - I opened this new issue as per your note.
https://github.com/energizedwork/webdriver-binaries-gradle-plugin/issues/8
