### ISSUE TITLE
Internet Explorer support for specifying 32 vs 64 bit version driver in config

### ISSUE THREAD

**Issue by masterautomator** [energizedwork/webdriver-binaries-gradle-plugin#8]
@erdi 

I am following up on our conversation thread from a different issue : https://github.com/energizedwork/webdriver-binaries-gradle-plugin/issues/7 

You have mentioned I open a new issue for requesting support for 32 bit vs 64 bit driver. There are well known issues with IE 64 bit version driver, and the workaround is to use the 32 bit version. In general, this maybe an option useful for other drivers too.

Would be great if we can have such support for 32 vs 64 bit requested version for this plug-in.

Thanks again!

**Comment by hermitmaster** [comment]
I am in favor of this change as well. Due to issues with the 64-bit driver, we exclusively use the 32-bit version.

**Comment by erdi** [comment]
[Specifying the architecture to be used for IEDriverServer](https://github.com/energizedwork/webdriver-binaries-gradle-plugin#extension-methods) is available in [1.4 version of the plugin](https://plugins.gradle.org/plugin/com.energizedwork.webdriver-binaries/1.4) which has just been released.

**Comment by masterautomator** [comment]
Thanks @erdi Will check it out asap and let you know the results

**Comment by masterautomator** [comment]
@erdi The change looks **good** as per my preliminary testing. I am able to use the x86 (32-bit) IE driver on a 64-bit system as per the documentation you supplied. 

I am guessing if I don't specify the architecture for the driver, it defaults to how it was before this change.

**Comment by erdi** [comment]
Yes, as described in the docs, IE driver architecture defaults to the
architecture of the operating system the build is running on.
